# Generated by Django 5.2.8 on 2025-11-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('event', 'seat_number')},
        ),
    ]
